#!/bin/sh

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

if ! grep -qE '^(v|Merge)|\[(FEAT|FIX|DOCS|STYLE|REFACTOR|CHORE|TEST)\]' "$1"; then
  echo "커밋 메시지는 '[FEAT]', '[FIX]', '[DOCS]', '[STYLE]', '[REFACTOR]', '[CHORE]', '[TEST]' 등으로 시작해야 합니다."
  exit 1
fi